# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'simple-ios-app-1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for simple-ios-app-1
  pod 'Firebase/Core'
end
